### ISSUE TITLE
`gt::tab_options` renders empty cell in table where it should be `<by_group>`

### ISSUE THREAD

**Issue by jacobvjk** [RMI-PACTA/workflow.multi.loanbook#110]
https://github.com/RMI-PACTA/workflow.multi.loanbook/blob/ec36aa68e2f4526a59d004a4e14a372217660174/vignettes/data_dictionary.Rmd#L37

it seems like the `<>` signs remove the cell entry

**Comment by cjyetman** [comment]
Ha! I can imagine why. Probably being interpreted as an empty html tag. I think I saw something about escaping certain strings. I'll look into it.

**Comment by cjyetman** [comment]
Seems like the `ihtml.active = TRUE` option introduces the problem, and `gt::fmt_passthrough()` can fix it.

```r
table <- data.frame(column = "<by_group>", typeof = "character")
gt::tab_options(gt::gt(table))
gt::tab_options(gt::gt(table), ihtml.active = TRUE)
gt::fmt_passthrough(gt::tab_options(gt::gt(table), ihtml.active = TRUE))
```

**Comment by jacobvjk** [comment]
that would be preferable over my direct escaping of <>
