### ISSUE TITLE
reconsider if `abcd_test_data` and `loanbook_test_data` should be exported

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/workflow.multi.loanbook#118]
maybe also `data_dictionary` if its primary purpose is to drive [the article/vignette page](https://rmi-pacta.github.io/workflow.multi.loanbook/articles/data_dictionary.html) and it's not intended to be accessed directly by a user?

AB#12145

**Comment by jdhoffa** [comment]
* `data_dictionary` should be exported
* `abcd_test_data` and `loanbook_test_data` should not

**Comment by cjyetman** [comment]
It appears that `abcd_test_data` and `loanbook_test_data ` are currently not used anywhere, and therefore probably should be removed completely?

https://github.com/search?q=repo%3ARMI-PACTA%2Fpacta.multi.loanbook%20abcd_test_data&type=code

https://github.com/search?q=repo%3ARMI-PACTA%2Fpacta.multi.loanbook+loanbook_test_data&type=code

**Comment by cjyetman** [comment]
draft PR to remove them completely #204

**Comment by jdhoffa** [comment]
For posterity, the datasets seem to have been introduced here:
https://github.com/RMI-PACTA/pacta.multi.loanbook.analysis/commit/a1d9b0b3584a23c6dcf14c9d17ba9599e59a7d87

**Comment by jdhoffa** [comment]
Indeed, I agree with @cjyetman that we can likely just remove them entirely
