### ISSUE TITLE
rename this repo/ package to `pacta.multi.loanbook`

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/workflow.multi.loanbook#121]
do the thing

**Comment by cjyetman** [comment]
#133 does all the code related parts of this, but it should be followed by renaming the repo in GitHub

**Comment by cjyetman** [comment]
also need to update here once complete
https://github.com/RMI-PACTA/rmi-pacta.r-universe.dev/blob/7ea749c74eca0d439e20b7c0e2d3b79895f0c7ad/packages.json#L82-L85

**Comment by jdhoffa** [comment]
The name of the package has been updated :-)

**Comment by cjyetman** [comment]
r-universe updated https://github.com/RMI-PACTA/rmi-pacta.r-universe.dev/commit/af5d6dc61206f7ff2d7d1c9ef32d249f6365a0c2
