### ISSUE TITLE
consider better names for the vignettes

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/workflow.multi.loanbook#136]
current vignette names include:
- "documentation of options in config.yml"
- "data dictionary"
- "cookbook"

These could probably be renamed with better/more descriptive names

**Comment by jdhoffa** [comment]
I can imagine two approaches here. One would be to name the vignettes for what they are:
* Configuration
* Data Dictionary
* Technical Cookbook

The other would be to name the vignettes for why they are useful to the user:
* Configuring your application
* Understanding the data
* Running the analysis

Not sure which of them I prefer, though I think I would lean towards the latter? 
What do you think @cjyetman @jacobvjk

**Comment by cjyetman** [comment]
I like the latter, because the "what they are" is already answered in the menu groupings, "Documentation" and "Cookbooks" (which also could be modified/changed/improved).

**Comment by jdhoffa** [comment]
Done!
