### ISSUE TITLE
consider having a `release` and `dev` version of the pkgdown website

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/workflow.multi.loanbook#151]
As the r2dii packages do, it's possible to automatically maintain two pkgdown websites, one for the "release" version (generated at the root level of the pkgdown website whenever a standard semantic version number is used in the DESCRIPTION) and a "dev" version for whatever is on main whenever a version number has four components, e.g. `0.0.0.9000`

how-to documented here: https://pkgdown.r-lib.org/reference/build_site.html#development-mode

**Comment by jdhoffa** [comment]
Makes sense
