### ISSUE TITLE
clearly identify the containing directory for every `filename_*` config option

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/workflow.multi.loanbook#160]
For all the `filename_*` type config options documented in https://rmi-pacta.github.io/pacta.multi.loanbook/articles/config_yml.html, we should clearly indicate the directory/path it should be found in, which currently can only be what's defined by either `dir_input` or `dir_output` (I think). Previously, it was a bit more obvious from the config option names, e.g. `filename_abcd` was obviously in `dir_abcd`, but now that we've consolidated everything into inputs and outputs we should be more clear about it in the documentation. Additionally, there are still some sub-directories that get created / are expected, e.g. `outputs/matched_loanbooks`, so we should be cautious to identify if certain `filename_*` type config options define the name of a file that actually lives in one of those sub-directories.

AB#12182

**Comment by jdhoffa** [comment]
@cjyetman to review/ investigate if this is still relevant, and indicate if it is, or close the issue if it isn't

**Comment by cjyetman** [comment]
@jdhoffa @jacobvjk I believe this is still relevant and even a priority...

The config file sets the directories and the filenames in two separate sections. For example, the `filename_scenario_tms` filename sets the filename of the TMS scenario data, but that file must also be in the directory defined by the `dir_input` parameter in the directories section. I think it would be prudent to explicitly mention in the config documentation which directory parameter defines the directory that each of the filename parameters files must live in.
