### ISSUE TITLE
consider archiving former repos that have been merged into this

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/workflow.multi.loanbook#165]
these repos should probably be archived now?
https://github.com/RMI-PACTA/pacta.multi.loanbook.analysis
https://github.com/RMI-PACTA/pacta.multi.loanbook.plot
https://github.com/RMI-PACTA/workflow.aggregate.loanbooks

**Comment by cjyetman** [comment]
@jdhoffa do you have admin permission for this?

**Comment by jdhoffa** [comment]
- [x] https://github.com/RMI-PACTA/workflow.aggregate.loanbooks
- [x] https://github.com/RMI-PACTA/pacta.multi.loanbook.analysis
- [x] https://github.com/RMI-PACTA/pacta.multi.loanbook.plot

**Comment by cjyetman** [comment]
@jacobvjk @jdhoffa maybe this should also be archived?
https://github.com/RMI-PACTA/pacta.aggregate.loanbook.plots

**Comment by jdhoffa** [comment]
All mentioned repositories have been publicly archived. 
Closing as complete
