### ISSUE TITLE
should `prepare_sector_split()` only run when `apply_sector_split = TRUE`?

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/workflow.multi.loanbook#174]
consider whether either...

in `prepare_abcd()`, `prepare_sector_split()` should only run conditionally if `apply_sector_split = TRUE` in the config
https://github.com/RMI-PACTA/pacta.multi.loanbook/blob/a973147fb9c9845e4fc39f537263824146446389/R/prepare_abcd.R#L22

or if `prepare_sector_split()` should test that `apply_sector_split = TRUE` in the config and otherwise exit out immediately

(or both)

As it is now, `prepare_abcd()` will always run `prepare_sector_split()`, and `prepare_sector_split()` will error if the sector split CSV is not found even if `apply_sector_split = FALSE` in the config.

AB#12037

**Comment by jdhoffa** [comment]
This seems like a bug/ unexpected behavior to me!

My desired behaviour would be that: 
- `prepare_abcd` with `apply_sector_split = TRUE` runs both steps
-  `prepare_abcd` with `apply_sector_split = FALSE` only runs `remove_inactive_companies`
- `prepare_sector_split` with `apply_sector_split = FALSE` errors out

@jacobvjk @cjyetman do you two agree? and does that make sense?

**Comment by cjyetman** [comment]
I think that's the same thing I said above, no?

**Comment by jdhoffa** [comment]
Indeed!
I was just agreeing in my own words to make sure we were on the same page

**Comment by cjyetman** [comment]
> This seems like a bug/ unexpected behavior to me!
> 
> My desired behaviour would be that:
> 
> * `prepare_abcd` with `apply_sector_split = TRUE` runs both steps
> * `prepare_abcd` with `apply_sector_split = FALSE` only runs `remove_inactive_companies`
> * `prepare_sector_split` with `apply_sector_split = FALSE` errors out
> 
> @jacobvjk @cjyetman do you two agree? and does that make sense?


I'm second guessing a part of this... if it's possible that one might use some of the utility functions here to build their own script, much like we've done with `prepare_abcd()`, then it's seemingly likely they might use the function `prepare_sector_split()`, and I'm thinking it doesn't make much sense to throw an error if the config has `apply_sector_split = FALSE`, but rather `prepare_sector_split()` should check the config and do whatever it should do relevant to what the config does but not throw an error that blows up completely anyone's process.

**Comment by jacobvjk** [comment]
> > This seems like a bug/ unexpected behavior to me!
> > My desired behaviour would be that:
> > 
> > * `prepare_abcd` with `apply_sector_split = TRUE` runs both steps
> > * `prepare_abcd` with `apply_sector_split = FALSE` only runs `remove_inactive_companies`
> > * `prepare_sector_split` with `apply_sector_split = FALSE` errors out
> > 
> > @jacobvjk @cjyetman do you two agree? and does that make sense?
> 
> I'm second guessing a part of this... if it's possible that one might use some of the utility functions here to build their own script, much like we've done with `prepare_abcd()`, then it's seemingly likely they might use the function `prepare_sector_split()`, and I'm thinking it doesn't make much sense to throw an error if the config has `apply_sector_split = FALSE`, but rather `prepare_sector_split()` should check the config and do whatever it should do relevant to what the config does but not throw an error that blows up completely anyone's process.

wouldn't this be solved by simply just keeping the if condition in `prepare_abcd()` and removing it from `prepare_sector_split()`? I agree that there may be a situation where someone could use `prepare_sector_split()` in their own script

**Comment by cjyetman** [comment]
> wouldn't this be solved by simply just keeping the if condition in `prepare_abcd()` and removing it from `prepare_sector_split()`? I agree that there may be a situation where someone could use `prepare_sector_split()` in their own script

depends on what the "this" being solved is... 

if it's achieving @jdhoffa's desired behavior, then no it would not solve it because at the moment @jdhoffa desires `prepare_sector_split()` to error out if `apply_sector_split = FALSE`

if it's to get this integration testing working, then yes it solves the problem there, though #184 already solves that with an in-between solution where `prepare_sector_split()` gives a warning and skips everything else when `apply_sector_split = FALSE`

**Comment by jacobvjk** [comment]
I don't think it makes sense for `prepare_sector_split()` to error out when `apply_sector_split = FALSE`. It should error out when the required inputs are not available or faulty for what it is instructed to do. When `apply_sector_split = FALSE`, it is basically instructed to do nothing, not even to load data sets that need to be available for its calculation. So in my view it should either be skipped or it should return invisibly with a warning. I don't have a strong view on which is better.  When `apply_sector_split = TRUE`, it is instructed to actually produce the sector split outputs. Now it should error out if it cannot do that. Equally, functions that may use the sector split later on (e.g. `prioritise_and_diagnose()`) should error out if they are instructed to use the sector split, but the file created with `prepare_sector_split()` cannot actually be found/used

**Comment by cjyetman** [comment]
Agreed. That's what I did in #184
