### ISSUE TITLE
find a way that allows integration testing without requiring manual clean up of test dirs for local testing

### ISSUE THREAD

**Issue by jacobvjk** [RMI-PACTA/workflow.multi.loanbook#188]
> running the tests locally seems a bit brittle. when I run them, I get this:
> 
> ```
> ✔ |          1 | 3-prioritise_and_diagnose [2.1s]            
> ⠏ |          0 | 4-analyse                                   [1] "Sankey plot (by sector) cannot be generated. Skipping!"
> [1] "Sankey plot (by sector and company) cannot be generated. Skipping!"
> [1] "Scatter plot exposure by alignment cannot be generated. Skipping!"
> Scatter plot BO/PO cannot be generated. Skipping!
> Scatter plot BO/PO cannot be generated. Skipping!
> Scatter plot BO/PO cannot be generated at company level. Skipping!
> Scatter plot BO/PO cannot be generated at company level. Skipping!
> ✔ |          1 | 4-analyse 
> ```
> 
> is that expected? It seems like `4-analyse` is run twice, once skipping, once successfully? Also, when I now rerun the test, I get an error in `1-prepare_abcd`, because the output directory already exists (i.e. it was not cleaned up after the first run) and the test expects no conditions. Although the condition is just the warning that the output directory already exists and will be overwritten, as per #179
> 
> ```
> ── Failed tests ─────────────────────────────────────────────
> Failure (test-1-prepare_abcd.R:28:3): with known input, runs without error
> Expected `prepare_abcd(config)` to run without any conditions.
> i Actually got a <simpleWarning> with text:
>   Output directory `dir_prepared_abcd` already exists. The existing directory will be removed and replaced with the output of the current run.
> ```

1 - yes, it is expected that those "sanky" lines get output to the console... it then forces testthat to reprint the test name line so that it is the most recent thing on the console, it's *not* actually running again

2 - I couldn't think of a clean way of clearing out the test files that are created during the test because they need to be intermingled with the files that need to be created pre-testing which are included in the repo. In the automated CI, it doesn't matter because a brand new clone is always made first that will always have the pre-files but not the post-files. I would dump them in a temp directory that gets deleted when the test are done, but they need to be intermingled with the input files that are already there. I can't make them use temporary files because we're using functions that have a side effect of creating files. catch-22

_Originally posted by @cjyetman in https://github.com/RMI-PACTA/pacta.multi.loanbook/issues/185#issuecomment-2451720594_
            

AB#12075

**Comment by jdhoffa** [comment]
A potential option here could be to use GH actions and CI/CD to run the integration test (rather than `testthat`, which tends to be geared more towards unit tests)
