### ISSUE TITLE
feat: add run_pacta.R

### ISSUE THREAD

**Issue by jacobvjk** [RMI-PACTA/workflow.multi.loanbook#19]
the part that runs standard pacta in bulk for all loan books/groups

AB#11599

**Comment by cjyetman** [comment]
so if I understand correctly, this new `run_pacta.R` should be a hybrid of these two scripts, or?
https://github.com/RMI-PACTA/workflow.aggregate.loanbooks/blob/main/run_pacta_in_bulk.R
https://github.com/RMI-PACTA/workflow.osfi/blob/main/batch_run_pacta.R

**Comment by jacobvjk** [comment]
the main differences are the following:
- workflow.aggregate.loanbooks contained additional optional steps to apply the sector split and to remove inactive companies.
- these two steps have now been moved to dedicated prepare_*.R scripts and do not have to be handled in run_pacta.R (see mural)
- simply reading abcd_final and the matched_prioritized loanbooks will do the trick
- workflow.aggregate.loanbooks also contains a step to add a "meta loan book". While I think this should be changed so that any type of loan book split can be returned, I think this will be a follow up task and that step can be retained for now.
- workflow.osfi does not contain anything else that needs to be accounted for in this transfer

**Comment by cjyetman** [comment]
- closed by #48
