### ISSUE TITLE
docs: Include samples visuals in the `README.md`

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/workflow.multi.loanbook#212]
People are drawn more to repositories with some kind of visual representation of what the software can do. This could be:
* a plot
* a diagram/ flowchart
* a .gif (terminal, etc.) outlining a use-case or interesting analysis

**Comment by jacobvjk** [comment]
[viz_readme.pdf](https://github.com/user-attachments/files/17833886/viz_readme.pdf)

@jdhoffa this covers multiple of the outputs that you get. Obviously nothing that helps the user understand exactly what this is, but if it is just for a pleasant README, we could start with this and get someone with some design skills and time at hand to come up with something better at some point

**Comment by jdhoffa** [comment]
Ok let me think on this one for a moment! Thank you

**Comment by jdhoffa** [comment]
@jacobvjk I think this looks great for now. We can come back to it later if we end up having time. 

Can you open a PR to add this to the `README.md`? 

Please put the `.pdf` in a directory under `man` (for example: https://github.com/RMI-PACTA/r2dii.plot/blob/main/man/figures/README-unnamed-chunk-2-1.png)
