### ISSUE TITLE
upkeep: Review and remove all `TODO`, `FIXME`, and any other comments used to kick cans down roads

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/workflow.multi.loanbook#213]
"Remove" here means: 
* The comment is reviewed
* An assessment is made if that comment is still relevant
* If it IS relevant, a GitHub issue is created explaining what needs to happen
* If it IS NOT relevant, the comment is deleted

---

[search for `TODO` in the code](https://github.com/search?q=repo%3ARMI-PACTA%2Fpacta.multi.loanbook+todo&type=code)
[search for `**LINK**` in the code](https://github.com/search?q=repo%3ARMI-PACTA%2Fpacta.multi.loanbook+**link**&type=code)

**Comment by jdhoffa** [comment]
Do this also for missing `LINK`s:
https://github.com/RMI-PACTA/pacta.multi.loanbook/blob/c0bc24e76f7f7b72d4c3e0bf9458011f0d4f4aa1/vignettes/cookbook.Rmd#L106

**Comment by cjyetman** [comment]
I think many of the "todo"s meant to prompt creating examples should simply be removed, especially those attached to unexported functions like the plotting functions.

**Comment by cjyetman** [comment]
I've reviewed all of these and there aren't an easy wins... these will all take some consideration from @jacobvjk I believe.

**Comment by jdhoffa** [comment]
That's ok! I didn't necessarily expect them to be easy wins (in terms of actually fixing them). 

The main goal of this issue is that we migrate them all into well-specified GitHub issues. A `TODO` (et.c) is likely to just get left/ forgotten about, context gets lost, and they just end up as tech debt hanging around the code

**Comment by jdhoffa** [comment]
Or did you mean that you also don't have the context to extract issues?
In that case, agreed probably this is a job for @jacobvjk

**Comment by cjyetman** [comment]
I just thought a bunch of them would be e.g. "todo" examples of functions that we are no longer exporting, but I think only 4 of them are like that... the rest I don't have enough context to know if they're still relevant.

**Comment by jdhoffa** [comment]
Got it ok. Let's triage this next sprint then. Likely a @jacobvjk ticket

**Comment by cjyetman** [comment]
and actually, all of the todo-examples-of-using-no-longer-exported-plotting-functions I think were already stripped... the remaining todos in the plotting functions are things that need more context than I have also.
