### ISSUE TITLE
docs: cookbook is too long

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/workflow.multi.loanbook#215]
This is a daunting scrollbar:
![Screenshot 2024-11-08 at 13 29 37](https://github.com/user-attachments/assets/9117e227-ed7d-4dee-a028-1515b2628de1)

Let's put in an effort to keep as much of the critical information as possible, but summarize and streamline as much of the cookbook as possible. 

We should avoid duplicating information (e.g. if something is denoted or explained in the data dictionary, then link to that, rather then explaining it again in the cookbook). 

This issue will be a meta-issue to track other issues that work towards this goal.

**Comment by cjyetman** [comment]
less is more or less more, but more is less less

**Comment by jdhoffa** [comment]
more or less

**Comment by cjyetman** [comment]
make it wider

**Comment by jdhoffa** [comment]
A lot of this was solved by https://github.com/RMI-PACTA/pacta.multi.loanbook/pull/255

Now one section is still a bit long, but that will be tracked in #263. 

Superseded by #263
