### ISSUE TITLE
docs: cookbook - document where the user can find each dataset

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/workflow.multi.loanbook#216]
I know we will have varying degrees of information about these datasets, but we should include as much as we can to guide the user where to get them, as they will certainly ask.

For example
Good: "ABCD can be purchased from Asset Impact"
Better: (include a link to their e-mail)

**Comment by jdhoffa** [comment]
@hodie do you see any issue with doing this? 
I don't see any other way for the user to access the appropriate data without clearly pointing them to Asset Impact.

**Comment by hodie** [comment]
I think that's fine. Similarly, we should provide links, not just names, for the scenario providers.

**Comment by hodie** [comment]
When I was reading through the guide from a user's perspective, I was thinking it should give some better pointers to were to get the data.
