### ISSUE TITLE
docs: Remove CRAN installation instructions until it is actually on CRAN

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/workflow.multi.loanbook#217]
We anticipate that it will be accepted to CRAN, but if it is not then these instructions will only be confusing (especially if we forget about them). 

https://github.com/RMI-PACTA/pacta.multi.loanbook/blob/c0bc24e76f7f7b72d4c3e0bf9458011f0d4f4aa1/vignettes/cookbook.Rmd#L210-L214

Relates to #210

**Comment by cjyetman** [comment]
Could maybe use ["selective HTML"](https://pkgdown.r-lib.org/reference/build_site.html#selective-html) to show the dev install instructions on the dev site and the CRAN install only on the release site.
