### ISSUE TITLE
docs: cookbook - Project Setup section must very clearly document how to write the default `config.yml` to your project directory

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/workflow.multi.loanbook#219]
The config vignette can go into more detail, but the Cookbook needs to be the source of truth to get thE "most basic" run working, and to do so, you must be able to easily create a default `config.yml`

For example here: 
https://github.com/RMI-PACTA/pacta.multi.loanbook/blob/c0bc24e76f7f7b72d4c3e0bf9458011f0d4f4aa1/vignettes/cookbook.Rmd#L254-L256

AB#12190

**Comment by jdhoffa** [comment]
Indeed, there don't seem to be any functions to generate a default config! I think this is something we should definitely add (and document). 

I see https://github.com/RMI-PACTA/pacta.multi.loanbook/blob/main/example.config.yml
But this requires the user to clone the package repo, which is unlikely to happen for most users.

**Comment by jdhoffa** [comment]
Updated issue description.

Acceptance criteria:
- [ ] Exported function that writes the default `config.yml` to some path (default should be the working directory that the function was called from. default name `config.yml`)
- [ ] Cookbook and Config vignettes should gain description of how to use this function 
- [ ] `example.config.yml` removed from the root of this repo (should probably be in the `inst` folder)

**Comment by jdhoffa** [comment]
Optionally, we could create a function that just sets up the entire default directory structure (with the `config.yml` included).
@cjyetman @jacobvjk what do you think?

**Comment by cjyetman** [comment]
> Optionally, we could create a function that just sets up the entire default directory structure (with the `config.yml` included). @cjyetman @jacobvjk what do you think?

I expect that some/most users will either
- already have the input data (in some location they prefer)
- will get the input data and put it in some location they prefer
- will have some institutional restrictions on where the input data can be stored, e.g. only accessed from a network or specific drive

the input directory is really the only one that needs to be created pre-process. All of the output directories are created automatically during the process, and if they are pre-created it will cause the scripts to prompt the user about deleting them and replacing them with new ones (as of #208).

All of that leads me to guess that a function pre-creating a suggested directory layout would not be very useful.

**Comment by jdhoffa** [comment]
Sounds good!
Then just a `config.yml` creating function it is :-)

**Comment by jdhoffa** [comment]
Closed in favour of #247
