### ISSUE TITLE
docs: `example.config.yml` out of date

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/workflow.multi.loanbook#221]
Rather annoying to make a reprex, but see the screenshot: 

![Screenshot 2024-11-08 at 14 27 37](https://github.com/user-attachments/assets/833397ae-3c1c-484e-b029-c1ae4a8a9816)

This is using the following directory structure:
![Screenshot 2024-11-08 at 14 28 21](https://github.com/user-attachments/assets/347a884f-b580-4d41-a8fd-ce6d1dfa1eab)

**Comment by jdhoffa** [comment]
I think a key is just missing from the `example.config.yml`

**Comment by cjyetman** [comment]
In the context of `prepare_abcd()`, `output_prepare_dir` is an internal variable that [should be set by `get_output_prepare_dir(config)`](https://github.com/RMI-PACTA/pacta.multi.loanbook/blob/c0bc24e76f7f7b72d4c3e0bf9458011f0d4f4aa1/R/prepare_abcd.R#L23C25-L23C55), which [should pull the key `dir_prepared_abcd` from your config](https://github.com/RMI-PACTA/pacta.multi.loanbook/blob/c0bc24e76f7f7b72d4c3e0bf9458011f0d4f4aa1/R/load_config.R#L25-L27), which is [included in the example config](https://github.com/RMI-PACTA/pacta.multi.loanbook/blob/c0bc24e76f7f7b72d4c3e0bf9458011f0d4f4aa1/example.config.yml#L4).

That being said, the error message could be better in the strange case that `output_prepare_dir` does not exist, or is `NULL` if for instance the `dir_prepared_abcd` key is not specified in the config... however, I can't really understand how you got to that point without failing from the previous checks that test for a valid value of `output_prepare_dir`:
https://github.com/RMI-PACTA/pacta.multi.loanbook/blob/c0bc24e76f7f7b72d4c3e0bf9458011f0d4f4aa1/R/prepare_abcd.R#L25-L26

**Comment by cjyetman** [comment]
Also bizarre because the `cli` command should not run unless the `output_prepare_dir` not only exists, but also contains a value that points to a directory that actually exists 🤯 

https://github.com/RMI-PACTA/pacta.multi.loanbook/blob/c0bc24e76f7f7b72d4c3e0bf9458011f0d4f4aa1/R/prepare_abcd.R#L28-L35

**Comment by jdhoffa** [comment]
¯\_(ツ)_/¯ 
I can pair if you want. I didn't do anything funky at all, just set-up the project based on the instructions given

**Comment by jdhoffa** [comment]
This was actually a bug! The config was in fact up to date.

**Comment by cjyetman** [comment]
#222 resolves the bug, does it then also resolve this issue?

**Comment by jdhoffa** [comment]
It does!
