### ISSUE TITLE
generate timestamped outputs

### ISSUE THREAD

**Issue by jacobvjk** [RMI-PACTA/workflow.multi.loanbook#23]
https://dev.azure.com/RMI-PACTA/2DegreesInvesting/_workitems/edit/10028

**Comment by cjyetman** [comment]
- related #22

**Comment by jacobvjk** [comment]
as per latest discussion, we do not aim for timestamped outputs, but follow the structure explained here: https://dev.azure.com/RMI-PACTA/2DegreesInvesting/_workitems/edit/10243
