### ISSUE TITLE
deal with plotting TODOs

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/workflow.multi.loanbook#237]
- related to #213 

@MonikaFu and @jacobvjk there a a few TODOs in the plotting functions here. Are these something @jacobvjk can/will handle, or something @MonikaFu will need to do / decide on?

https://github.com/RMI-PACTA/pacta.multi.loanbook/blob/03d3c10346d3c0a0bb132cb225a3cce01bfb307b/R/plot_sankey.R#L110-L119

https://github.com/RMI-PACTA/pacta.multi.loanbook/blob/03d3c10346d3c0a0bb132cb225a3cce01bfb307b/R/plot_aggregate_loanbooks.R#L130-L141

https://github.com/RMI-PACTA/pacta.multi.loanbook/blob/03d3c10346d3c0a0bb132cb225a3cce01bfb307b/R/plot_aggregate_loanbooks.R#L373-L388

**Comment by jacobvjk** [comment]
the latter two TODOs are already addressed here #251 

@MonikaFu I don't know what the TODO in `plot_sankey.R` refers to. The sankey plot already colors based on alignment. Not sure how this differs

**Comment by jdhoffa** [comment]
If there is no clear idea what `# TODO: colour the companies if fully aligned or not` refers to by Friday, then you can just remove the comment and close out this issue

**Comment by MonikaFu** [comment]
you can remove it. I'm not sure what it is about either.
