### ISSUE TITLE
feat: optimize plots and visuals for the cookbook

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/workflow.multi.loanbook#253]
User Story: 
* As a reader of the cookbook, I would like to easily see and understand all visuals

Acceptance Criteria:
- [ ] All titles, labels, etc. in all plots should be larger than or equal to the size of the text content in the cookbook (e.g. in screenshot below, all plot font sizes should be increased to at least the size of "An example plot..." 

![Screenshot 2024-11-20 at 12 36 48](https://github.com/user-attachments/assets/78d0a2d2-05af-4d23-8f31-0f003351a90d)

**Comment by cjyetman** [comment]
These [plots](https://github.com/RMI-PACTA/pacta.multi.loanbook/tree/main/man/figures) were made by @jacobvjk offline, so I don't have the code or data to recreate them, which makes it rather infeasible for me to change font sizes.

**Comment by jdhoffa** [comment]
Ah darn, I thought these were in a `.Rmd` or something like that. All good!

In that case, I will re-assign this ticket to @jacobvjk (and we can discuss capacities next week to see if that's doable)
