### ISSUE TITLE
pkgdown: original cookbook seems to still exist in the pkgdown site

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/workflow.multi.loanbook#265]
In #255 we split the cookbook into various sections, e.g.: https://rmi-pacta.github.io/pacta.multi.loanbook/articles/cookbook_overview.html

However, when navigating to the pkgdown site, it seems that links to the _old_ version of the cookbook still remain, and are accessible, see: https://rmi-pacta.github.io/pacta.multi.loanbook/articles/cookbook.html (even though the `cookbook.Rmd` that generates this was removed). 

I would expect navigating to the old link should yield a 404 not found error

**Comment by cjyetman** [comment]
I imagine this is a similar problem to what was discussed here https://github.com/RMI-PACTA/r2dii.data/pull/405

**Comment by jdhoffa** [comment]
I think you are correct, which is why I tagged you :)
