### ISSUE TITLE
add examples to exported functions

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/workflow.multi.loanbook#272]
inline comments removed in #273 and replaced with this issue

https://github.com/RMI-PACTA/pacta.multi.loanbook/blob/ccfd776154e462e271d1ad89322209faa8e96bff/R/analyse.R#L17-L21

https://github.com/RMI-PACTA/pacta.multi.loanbook/blob/ccfd776154e462e271d1ad89322209faa8e96bff/R/prioritise_and_diagnose.R#L19-L21

https://github.com/RMI-PACTA/pacta.multi.loanbook/blob/ccfd776154e462e271d1ad89322209faa8e96bff/R/prepare_abcd.R#L18-L20

https://github.com/RMI-PACTA/pacta.multi.loanbook/blob/ccfd776154e462e271d1ad89322209faa8e96bff/R/match_loanbooks.R#L19-L21

**Comment by cjyetman** [comment]
To be honest, I'm not sure an example of how to use these is very informative, e.g.
``` r
config <- "path/to/config.yml"
prepare_abcd(config)
```

**Comment by cjyetman** [comment]
gonna close this ticket because it doesn't seem worthwhile

**Comment by jdhoffa** [comment]
I'm not sure that CRAN accepts packages that don't have examples?

**Comment by cjyetman** [comment]
hmmm.... re-opening then

**Comment by jdhoffa** [comment]
https://r-pkgs.org/release.html

See the "First release" section of this page (bullet 5)

**Comment by cjyetman** [comment]
sounds ambiguous, but better safe than sorry 
https://github.com/DavisVaughan/extrachecks?tab=readme-ov-file#you-have-exported-functions-that-dont-have-examples

**Comment by cjyetman** [comment]
setting as `priority` because this should be done before CRAN release

**Comment by jdhoffa** [comment]
> sounds ambiguous, but better safe than sorry https://github.com/DavisVaughan/extrachecks?tab=readme-ov-file#you-have-exported-functions-that-dont-have-examples

This seems to suggest that for functions that are used for their side effects (which I believe all of our functions are?) that examples aren't necessary.

@cjyetman what do you think? we could try a submission first and see what happens

**Comment by cjyetman** [comment]
yeah, but why screw around? If they generally look for that, I'd just put it in there even though it's kinda nonsensical.

**Comment by jdhoffa** [comment]
My only worry is that since our functions create directories, and since CRAN runs examples on their server, they may not want us screwing around creating directories 😅 

Honestly not sure what the appropriate approach is here

**Comment by cjyetman** [comment]
examples using `dontrun`?

**Comment by jdhoffa** [comment]
e.g. https://github.com/RMI-PACTA/pactaverse/blob/1751ab21d622dfbf999e85a5e748d1ffb5e00471/R/update.R#L10-L12

**Comment by cjyetman** [comment]
for example https://github.com/RMI-PACTA/r2dii.match/blob/72e74d8bb2a33d83e27f7def65088dcc186ba8c1/R/match_name.R#L64-L122

or 
``` r
#' @examples
#' \dontrun{
#' config <- "path/to/config.yml"
#' prepare_abcd(config)
#' }
```
