### ISSUE TITLE
integrate new `sector_classification` argument of `r2dii.match::match_name()`

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/workflow.multi.loanbook#277]
- depends on https://github.com/RMI-PACTA/r2dii.match/pull/509

A new `sector_classification` argument is being added to `r2dii.match::match_name()` to replace the mechanism of using `options(r2dii.match.sector_classifications = own)`. Once this lands, we will need to adapt here, specifically...

https://github.com/RMI-PACTA/pacta.multi.loanbook/blob/76e8cbd718fcf7687acb3774dfdf6389ea031d3f/R/match_loanbooks.R#L143-L161

**Comment by jdhoffa** [comment]
Maybe closed by #279
