### ISSUE TITLE
consider better formatting here to make the package names more clear

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/workflow.multi.loanbook#295]
https://github.com/RMI-PACTA/pacta.multi.loanbook/blob/28c1b676782653b156a0d14781625a65ba8a027c/vignettes/cookbook_preparatory_steps.Rmd#L195-L199

renders as
https://rmi-pacta.github.io/pacta.multi.loanbook/articles/cookbook_preparatory_steps.html#required-r-packages

**Comment by cjyetman** [comment]
This is probably overkill and it still doesn't avoid wrapping the version requirement in "`" when it exists 😕 

``` r
imports <- utils::packageDescription("pacta.multi.loanbook")[["Imports"]]
imports <- unlist(strsplit(x = imports, split = ",[[:space:]]"))
cat(paste0("`", paste0(imports, collapse = "`, `"), "`"))
#> `cli (>= 3.2.0)`, `config`, `dplyr`, `ggplot2`, `glue`, `networkD3`, `r2dii.analysis (>= 0.3.0)`, `r2dii.data (>= 0.5.0)`, `r2dii.match
#> (>= 0.3.0)`, `r2dii.plot (>= 0.4.0)`, `readr (>= 2.0.0)`, `readxl`, `rlang`, `scales`, `tidyr`, `webshot`, `yaml`, `yesno`
```

`cli (>= 3.2.0)`, `config`, `dplyr`, `ggplot2`, `glue`, `networkD3`, `r2dii.analysis (>= 0.3.0)`, `r2dii.data (>= 0.5.0)`, `r2dii.match (>= 0.3.0)`, `r2dii.plot (>= 0.4.0)`, `readr (>= 2.0.0)`, `readxl`, `rlang`, `scales`, `tidyr`, `webshot`, `yaml`, `yesno`

maybe this is not that important? 🤣

**Comment by jdhoffa** [comment]
I'm actually in favour of this!
