### ISSUE TITLE
consider parameterizing the text here so it's correct across dev and release versions of the docs (as done above)

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/workflow.multi.loanbook#296]
https://github.com/RMI-PACTA/pacta.multi.loanbook/blob/28c1b676782653b156a0d14781625a65ba8a027c/vignettes/cookbook_preparatory_steps.Rmd#L211-L221

**Comment by jacobvjk** [comment]
not sure what the difference should be here between dev and release. Can you elaborate?

**Comment by cjyetman** [comment]
I think I was thinking at the time that currently one cannot install from CRAN, but it suggests that you can. But that's pretty minor and soon enough you will be able to, so reading this now I don't think there's any point in changing it.

**Comment by cjyetman** [comment]
https://rmi-pacta.github.io/pacta.multi.loanbook/articles/cookbook_preparatory_steps.html#required-software

now says
> You can install the package from the RStudio CRAN mirror by running the following command in R:
> 
> [install.packages](https://rdrr.io/r/utils/install.packages.html)("pacta.multi.loanbook")
> You can install the development version of pacta.multi.loanbook from GitHub with:
> 
> # install.packages("pak")
> [pak](https://pak.r-lib.org/reference/pak.html)::pak("RMI-PACTA/pacta.multi.loanbook")
> We use the [pak package](https://pak.r-lib.org/index.html) as a simple [tool to install packages from GitHub](https://pak.r-lib.org/reference/pak.html).


https://rmi-pacta.github.io/pacta.multi.loanbook/dev/articles/cookbook_preparatory_steps.html#required-software

now says

> You can install the development version of pacta.multi.loanbook from GitHub with:
> 
> # install.packages("pak")
> [pak](https://pak.r-lib.org/reference/pak.html)::pak("RMI-PACTA/pacta.multi.loanbook")
> We use the [pak package](https://pak.r-lib.org/index.html) as a simple [tool to install packages from GitHub](https://pak.r-lib.org/reference/pak.html).

closing
