### ISSUE TITLE
consider using 2023 scenarios in the default example

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/workflow.multi.loanbook#299]
https://github.com/RMI-PACTA/pacta.multi.loanbook/blob/28c1b676782653b156a0d14781625a65ba8a027c/inst/default_config.yml#L9-L20

- related #220

**Comment by jdhoffa** [comment]
Sort of relates to #220

**Comment by jdhoffa** [comment]
- [ ] Also change the scenario file names to match the `2023` files that we have on the PACTA website
