### ISSUE TITLE
docs: add clear documentation defining how to set the `start_year` value

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/workflow.multi.loanbook#308]
In the cookbook

**Comment by jacobvjk** [comment]
Actually, the cookbook does not go into detail how to set the individual paramters of the config.yml. Instead it refers to the vignette that documents the config file. I do not think it makes sense to add a technical description of how and where to set the start_year as we would then have to do it for other parameters as well, for consistency. I am instead adding a comment to the general description of the scenario files.

**Comment by cjyetman** [comment]
note that setting the `start_year` parameter is indeed mentioned quite clearly in the cookbook here
https://github.com/RMI-PACTA/pacta.multi.loanbook/blob/83842f2eb3b9407b72676f7a11a9234a85531482/vignettes/cookbook_running_the_analysis.Rmd#L144
