### ISSUE TITLE
docs: in project setup, we may want to document that the user should start a new RStudio project

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/workflow.multi.loanbook#322]
@daisy-pacheco flagged difficulty runing the first step of the analysis. 

She ran:
``` r
> pacta.multi.loanbook::prepare_abcd(config_path)
Error in config::get(file = config) : 
  Config file config.yml not found in current working directory or parent directories
> getwd()
[1] "/Users/daisypacheco"
```

and realized that she had to switch directories to project directory relevant to the analysis. 

A quick note indicating that the user should start a new RStudio project might help this:
https://rmi-pacta.github.io/pacta.multi.loanbook/articles/cookbook_preparatory_steps.html#project-setup

**Comment by cjyetman** [comment]
though keep in mind, the user should be able to run these functions from any working directory assuming `config_path` is appropriately defined

**Comment by jdhoffa** [comment]
Daisy was just following the default instructions. 
`config_path` was set to `config.yml`, but it didn't work as the R session wasn't set in the same WD as the path

(I think setting a `config_path` that is separate from the RStudio project is an advanced use case, for someone that is already familiar with R and RStudio)

**Comment by cjyetman** [comment]
The cookbook gives the example

``` r
library(pacta.multi.loanbook)
config_path <- "config.yml"
```

I'm not arguing that there's not confusion, that is clear. Just keep in mind that it may be worse to encourage users to not look at the values and set them properly and just run it with whatever default is there rather than clearly explaining to them that the expectation is that they set the values appropriately.

e.g. maybe that example should be more clearly labeled as **this is an example, please specify the proper path to your config.yml file**

I just think there's no way to ensure that a user can simply copy-paste every command they find in the cookbook and expect things to work properly without considering the values they have in there, and maybe it's better to make that clear than try to obfuscate it.

**Comment by jdhoffa** [comment]
Our goal should be for a user to be able to follow the cookbook exactly as given, and be able to come up with an output... I think any assumption on their end of inferring any particular set-up step gets us further away from that. 

We need to anticipate very novice users

**Comment by jdhoffa** [comment]
So indeed, I think flagging that they _should_ start a new project, and define their config in that project, is reasonable

**Comment by jdhoffa** [comment]
I agree, we can't determine every particular of their set-up, but we need to give enough info for a motivated beginner to be able to have a chance at running it properly

**Comment by cjyetman** [comment]
> Our goal should be for a user to be able to follow the cookbook exactly as given, and be able to come up with an output... I think any assumption on their end of inferring any particular set-up step gets us further away from that.
> 
> We need to anticipate very novice users

yeah, but.... this is basically impossible... they 100% have to edit the config file that's created by `[initialise_default_project()](https://rmi-pacta.github.io/pacta.multi.loanbook/reference/initialise_default_project.html)` to match what inputs they have/use

so for instance, maybe
``` r
library(pacta.multi.loanbook)
config_path <- "config.yml"
```
should be changed to 
``` r
library(pacta.multi.loanbook)
config_path <- "path/to/your/config.yml"
```
?

**Comment by cjyetman** [comment]
like, I think changing the example to 
``` r
library(pacta.multi.loanbook)
config_path <- "path/to/your/config.yml"
```
is not only easier for us to do, it's likely easier for the user than having an additional step of making the user create a new RStudio project which goes far out-of-scope and has lots of external parameters?

**Comment by cjyetman** [comment]
in general, I think any example code that references a local path should be written in a way that is obvious that the path must be edited to be something relevant to where it's being run, e.g. we have this in the cookbook as well
```r
library(pacta.multi.loanbook)
initialise_default_project(path = "path/to/project_folder")
```

and e.g. in the functions' documentation
``` r
if (FALSE) { # \dontrun{
config <- "path/to/config.yml"
prepare_abcd(config)
} # }
```

**Comment by jdhoffa** [comment]
I'm in favour of that

**Comment by jacobvjk** [comment]
agree that we should generally make clear that we expect users to set paths to any input files they may end up using. I don't think that is asking more than standard PACTA
