### ISSUE TITLE
ABCD has changed their column name from `lei` to `LEI`

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/workflow.multi.loanbook#328]
We need to adapt our code accordingly

**Comment by jacobvjk** [comment]
I think there are broadly two options here, if we want this to be backwards compatible.

One option would be to put the burden on the users, i.e. either let them define if the col name is spelled in uppercase or lowercase letters (probably in the config file, although that would be a pretty weird thing to configure) or explain in the cookbook that they may need to change the name in the raw data file (complicated and we probably do not want them to have to fiddle around in the raw data ideally).

The other option would be to implement some logic that tries to determine which format to look for. We could try to read the names of the sheet in first and determine which of spellings is used to then adjust the expected columns. I don't love this implementation, but it might be the best way forward.
