### ISSUE TITLE
cookbook: Figure numbers should be defined programatically

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/workflow.multi.loanbook#343]
And enumeration should restart on every chapter

**Comment by jdhoffa** [comment]
Unless it's in physical print (leather-bound)

**Comment by jacobvjk** [comment]
it seems like using bookdown is the standard answer to this

- https://bookdown.org/yihui/rmarkdown-cookbook/figure-number.html
- https://stackoverflow.com/questions/51730846/auto-numbering-of-figure-and-table-captions-for-html-output-in-r-markdown

I wonder if that's worth it. Also notice that there are references to certain figure numbers in the text, so these would have to have variable references too.

**Comment by jdhoffa** [comment]
Not worth it!! Closing without action.
