### ISSUE TITLE
Release pacta.multi.loanbook 0.1.0

### ISSUE THREAD

**Issue by jacobvjk** [RMI-PACTA/workflow.multi.loanbook#349]
First release

- [ ] [usethis::use_news_md()](https://usethis.r-lib.org/reference/use_news_md.html) _(not required for initial GH release)_
- [ ] [usethis::use_cran_comments()](https://usethis.r-lib.org/reference/use_cran_comments.html) _(not required for initial GH release)_
- [x] Update (aspirational) install instructions in README
- [x] Proofread Title: and Description:
- [x] Check that all exported functions have @returns and @examples
- [x] Check that Authors@R: includes a copyright holder (role ‘cph’)
- [x] Check licensing of included files
- [x] Review https://github.com/DavisVaughan/extrachecks

Prepare for release:

- [x] git pull
- [x] Check [current CRAN check results](https://cran.rstudio.org/web/checks/check_results_r2dii.match.html)
- [x] Check if any deprecation processes should be advanced, as described in [Gradual deprecation](https://lifecycle.r-lib.org/articles/communicate.html#gradual-deprecation)
- [ ] [Polish NEWS](https://style.tidyverse.org/news.html#news-release) _(not required for initial GH release)_
- [x] urlchecker::url_check()
- [x] devtools::build_readme()
- [x] devtools::check(remote = TRUE, manual = TRUE)
- [x] devtools::check_win_devel()
- [x] revdepcheck::revdep_check(num_workers = 4)
- [ ] Update cran-comments.md _(not required for initial GH release)_
- [x] git push
- [x] Draft blog post

Submit to CRAN:

- [x] usethis::use_version('minor')
- [ ] devtools::submit_cran() _(not required for initial GH release)_
- [ ] Approve email _(not required for initial GH release)_

Wait for CRAN...

- [ ] Accepted 🎉 _(not required for initial GH release)_
- [x] git push
- [x] Finish & publish blog post
- [x] Add link to blog post in pkgdown news menu
- [x] usethis::use_github_release()
- [x] usethis::use_dev_version(push = TRUE)
- [x] Share on social media

**Comment by jacobvjk** [comment]
@jdhoffa It seems like it is not too common to have anything particular in the NEWS.md for the first CRAN submission. I checked some tidyverse examples and their NEWS tend to be populated starting with releases > 0.1.0.

**Comment by jdhoffa** [comment]
Ah indeed! NEWS should be empty. 

The changelog starts after the package is on CRAN

**Comment by jacobvjk** [comment]
> Ah indeed! NEWS should be empty.
> 
> The changelog starts after the package is on CRAN

which contradicts this to some degree: https://r-pkgs.org/release.html#sec-release-initial

Maybe we do this?
```
# pacta.multi.loanbook 0.1.0

* Initial CRAN submission.
```

**Comment by jacobvjk** [comment]
a few check boxes gained comment:  _(not required for initial GH release)_

**Comment by jdhoffa** [comment]
Woohoo!
