### ISSUE TITLE
consider warning if `webshot::is_phantomjs_installed() == FALSE` instead of error

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/workflow.multi.loanbook#356]
https://github.com/RMI-PACTA/pacta.multi.loanbook/blob/e285309b8abd20ef0a37836cc3d84f36fa136017/R/plot_sankey.R#L150-L160

Not sure we can expect that CRAN has installed phantomJS with `webshot::install_phantomjs()`, so we may need to make this a warning instead of an error? @jdhoffa 

---

or skip the `analyze()` test with something like
``` r
testthat::skip_if(
  isFALSE(webshot::is_phantomjs_installed()),
  "Skipped because `phantomjs` is needed for this test."
)
```

**Comment by jdhoffa** [comment]
I think that makes sense!!

**Comment by jdhoffa** [comment]
Reduce the `cli::cli_abort` to a `cli::cli_warn` please (with an informative message)
