### ISSUE TITLE
pkgdown website was completely deleted

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/workflow.multi.loanbook#372]
here: https://github.com/RMI-PACTA/pacta.multi.loanbook/commit/59def5bb4c6a523636cb0eb14dbc761352760774
triggered by: https://github.com/RMI-PACTA/pacta.multi.loanbook/commit/6e3dc971497ddbf98e62967ac495a1377fed5760
in this action: https://github.com/RMI-PACTA/pacta.multi.loanbook/actions/runs/12395029699

**Comment by jdhoffa** [comment]
Well that's not good! ahahaha

**Comment by cjyetman** [comment]
release site (https://rmi-pacta.github.io/pacta.multi.loanbook/) restored by going to https://github.com/RMI-PACTA/pacta.multi.loanbook/actions/workflows/pkgdown.yaml and manually running the action on the tag v0.1.0

but then subsequently manually running the action on main wipes the whole thing again... so something is off when the action runs on main (dev version of the pkgdown site)
