### ISSUE TITLE
parameterize `abcd_removed_inactive_companies.csv` filename

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/workflow.multi.loanbook#38]
Following the pattern with other filenames, `abcd_removed_inactive_companies.csv` should probably be added to the config rather than the filename being hard-coded into the script

https://github.com/RMI-PACTA/workflow.multi.loanbook/blob/c3e825cb5a45f09c3ca3a97881f05460bf99667e/prepare_sector_split.R#L80-L83

Edit: ⚠️ now that I understand that this is originally an output file (from [prepare_abcd.R](https://github.com/RMI-PACTA/workflow.multi.loanbook/blob/c3e825cb5a45f09c3ca3a97881f05460bf99667e/prepare_abcd.R#L164-L168)), adding it to the config may not be the right thing to do

**Comment by cjyetman** [comment]
@jacobvjk I think this should be closed?

**Comment by jacobvjk** [comment]
yes, I think this can be closed. I believe the removed companies file is also used elsewhere in the code, so it should probably not be possible to save it under a different name somewhere
