### ISSUE TITLE
improve warning about change in unique companies after sector split

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/workflow.multi.loanbook#74]
Currently when I run `run_match_prioritize()`, and more specifically `apply_sector_split_to_loans()`, with the test loanbooks and data that I have, I get all of these warnings. To be honest, I'm not sure if that's bad (probably, because it's a warning?), I'm not sure *how bad* that is (e.g. going from 1 to 132 seems dramatic, but maybe that's normal?), and I don't have any idea of how to fix it or what to look at. It would be advantageous to improve this a bit. Additionally, I suspect if this happens to 1 loanbook it's likely to happen in others (?), so when one runs `run_match_prioritize()` they'll likely get a series of these warnings one after another, and it's not clear which loanbook a given warning message is related to, so maybe we could improve that?

``` r
run_match_prioritize(config_path)
#> Warning messages:                                                                             
#> 1: ! Applying the sector split has lead to changes in the number of unique companies covered in
#>   the analysis.
#> ℹ Prior to the split, there was 1 unique company.
#> ℹ After the split, there are 74 unique companies. 
#> 2: ! Applying the sector split has lead to changes in the number of unique companies covered in
#>   the analysis.
#> ℹ Prior to the split, there was 1 unique company.
#> ℹ After the split, there are 84 unique companies. 
#> 3: ! Applying the sector split has lead to changes in the number of unique companies covered in
#>   the analysis.
#> ℹ Prior to the split, there was 1 unique company.
#> ℹ After the split, there are 51 unique companies. 
#> 4: ! Applying the sector split has lead to changes in the number of unique companies covered in
#>   the analysis.
#> ℹ Prior to the split, there was 1 unique company.
#> ℹ After the split, there are 76 unique companies. 
#> 5: ! Applying the sector split has lead to changes in the number of unique companies covered in
#>   the analysis.
#> ℹ Prior to the split, there was 1 unique company.
#> ℹ After the split, there are 115 unique companies. 
#> 6: ! Applying the sector split has lead to changes in the number of unique companies covered in
#>   the analysis.
#> ℹ Prior to the split, there was 1 unique company.
#> ℹ After the split, there are 132 unique companies. 
```

**Comment by cjyetman** [comment]
@jdhoffa @jacobvjk I think this is still relevant, though I haven't seen these warnings recently because I haven't done any testing with `apply_sector_split: TRUE` recently. Basically, for every loanbook that is processed, a user will get one of these warnings, so one can imagine that if a user was processing hundreds or even thousands of loan books at a time, these warnings would get cumbersome. I don't currently have a good idea about how to address this, but I think it's worth keeping this issue open and considering how to improve it.

**Comment by jdhoffa** [comment]
Since this is user-facing, I think it makes sense to flag it as a priority.

**Comment by jacobvjk** [comment]
this should be two tasks, it is definitely a bug that the message identifies only company prior to the split.

**Comment by jacobvjk** [comment]
so we have one suggested way of handling this linked in the draft PR. If you do not fundamentally disagree with that approach, I can open the PR

**Comment by cjyetman** [comment]
> so we have one suggested way of handling this linked in the draft PR. If you do not fundamentally disagree with that approach, I can open the PR

I back that strategy (#240)
