### ISSUE TITLE
there are two `remove_inactive_companies` options

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/workflow.multi.loanbook#84]
There are two options in the config file both named `remove_inactive_companies`, though in different sections of the config so not conflicting with each other. @jacobvjk can you confirm that both are necessary, and might you have a suggestion for further distinguishing them (beyond simply existing in a different section)?

https://github.com/RMI-PACTA/workflow.multi.loanbook/blob/bfdd711a177b3991d8397335161149a077803776/example.config.yml#L23

https://github.com/RMI-PACTA/workflow.multi.loanbook/blob/bfdd711a177b3991d8397335161149a077803776/example.config.yml#L48-L49

**Comment by jacobvjk** [comment]
we do not need this option twice. Given the current logic of the `config.yml`, I would suggest we keep the option in `prepare_abcd`, as this is where the inactive companies are actually removed. Any other function that uses the flag should use the exact same config
